version: "3.8"
services:
  natechapman_portfolio_website:
    image: n8erade/natechapman-portfolio:latest
    ports:
      - 8080:80
    build:
      context: ../website
      dockerfile: ../docker/website.dockerfile

  #  entrypoint: ['/bin/sh', 'npm i && npm run dev']
  #  ports:
  #    - 8000:8000
  #  working_dir: /srv/app
  #  volumes: 
  #    - type: bind
  #      source: ./website_frontend/*
  #      target: /srv/app
  #  tty: true



  #docker.io/n8erade/private/natechapman-portfolio-website:latest